language: clojure
lein: lein
dist: bionic
install:
- sudo apt-get install ansible
script: 
- lein test
- lein uberjar
- ansible-playbook -i e_inventory.yml e_playbook.yml
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host rickysquid.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key apper@rickysquid.org pwd
